"""
SentinelOps — Structured Root-Cause Analysis Schemas
Fits into: apps/api-server/src/agents/rca_structured.py
Integrates with: causality/, retrieval/, evaluation/scorers/
"""

from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Literal
from datetime import datetime


class EvidenceItem(BaseModel):
    """A single piece of normalized evidence from any source."""
    evidence_id: str = Field(..., description="Unique identifier for this evidence fragment")
    source: Literal["metrics", "logs", "deployment", "alert", "topology", "manual"]
    timestamp: datetime
    service: str = Field(..., description="Service or component this evidence relates to")
    signal: str = Field(..., description="What was observed, e.g. 'p99_latency_spike'")
    value: Optional[str] = Field(None, description="Raw value or snippet")
    severity: Literal["info", "warning", "critical", "unknown"] = "unknown"
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)


class SynthesizedNarrative(BaseModel):
    """Output of the EvidenceSynthesisAgent. Unified timeline fed into RCA."""
    narrative_id: str
    incident_id: str
    summary: str = Field(..., description="2-3 sentence natural-language summary of what happened")
    timeline: List[EvidenceItem] = Field(..., description="Chronologically ordered, correlated events")
    correlations: List[str] = Field(default_factory=list, description="Observed cross-source correlations")
    anomalies: List[str] = Field(default_factory=list, description="Anomalous signals flagged")
    missing_telemetry: List[str] = Field(default_factory=list, description="Gaps that could resolve ambiguity")
    primary_affected_service: str
    confidence_per_source: dict = Field(default_factory=dict)


class RunbookMatch(BaseModel):
    """A retrieved runbook or historical incident pattern."""
    runbook_id: str
    title: str
    mechanism_type: str
    similarity_score: float = Field(ge=0.0, le=1.0)
    relevant_section: Optional[str] = None


class CandidateCause(BaseModel):
    """
    Structured root-cause hypothesis generated by the LLM.
    Replaces heuristic candidate generation in the causality module.
    """
    cause_id: str = Field(..., description="UUID or deterministic hash for this candidate")
    description: str = Field(
        ...,
        description="Specific, evidence-bound description. Must name services, versions, or metrics."
    )
    affected_service: str = Field(..., description="Primary service impacted")
    triggering_event: str = Field(
        ...,
        description="The first event in the timeline that initiated the failure chain"
    )
    evidence_support: List[str] = Field(
        ...,
        description="List of evidence_ids that directly support this hypothesis"
    )
    evidence_against: List[str] = Field(
        default_factory=list,
        description="Evidence that contradicts or weakens this hypothesis"
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="LLM-estimated confidence. Will be recalibrated by UncertaintyEngine."
    )
    mechanism_type: str = Field(
        ...,
        description="Must map to a known category: deployment_error, resource_exhaustion, "
                      "cascade_failure, configuration_drift, dependency_failure, "
                      "network_partition, data_corruption, unknown"
    )
    runbook_matches: List[RunbookMatch] = Field(
        default_factory=list,
        description="Retrieved historical patterns that resemble this cause"
    )
    specificity_score: Optional[float] = Field(
        None,
        description="Computed post-generation: does it name exact entities?"
    )
    evidence_coverage: Optional[float] = Field(
        None,
        description="Computed post-generation: what fraction of anomalies does it explain?"
    )
    counterfactual: str = Field(
        ...,
        description="What would have prevented this? Used for remediation generation."
    )

    @property
    def title(self) -> str:
        return self.description

    @property
    def pattern_id(self) -> str:
        return self.cause_id

    @property
    def cause_service(self) -> str:
        return self.affected_service

    @property
    def pattern_match_score(self) -> float:
        return self.confidence

    @property
    def supporting_item_keys(self) -> List[str]:
        return self.evidence_support

    @property
    def required_keywords(self) -> List[str]:
        import re
        words = re.findall(r"\b[a-zA-Z0-9_-]+\b", f"{self.description} {self.triggering_event}")
        return [w.lower() for w in words if len(w) > 3]

    @field_validator("description")
    @classmethod
    def description_must_be_specific(cls, v: str) -> str:
        """Guard against generic hypotheses at the schema level."""
        generic_terms = ["performance issue", "deployment problem", "high load", "slow response", "error rate"]
        lower = v.lower()
        if any(term in lower for term in generic_terms) and not any(
            specific in lower for specific in ["commit", "version", "shard", "pod", "instance", "p99", "cpu", "memory", "timeout"]
        ):
            raise ValueError(f"Description too generic: {v}. Must reference specific services, metrics, or versions.")
        return v


class CandidateList(BaseModel):
    """Wrapper model for candidate list structured output."""
    candidates: List[CandidateCause]


class RootCauseAnalysisOutput(BaseModel):
    """Final structured output from the RCA node."""
    incident_id: str
    candidates: List[CandidateCause] = Field(..., min_length=1, max_length=5)
    selected_candidate_id: Optional[str] = None
    selection_rationale: Optional[str] = None
    ambiguity_state: Literal[
        "stable_cause",
        "competing_causes",
        "insufficient_evidence",
        "temporally_unstable",
        "observation_conflict"
    ] = "stable_cause"
    uncertainty_assessment: Optional[dict] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# --- Scoring helpers used by evaluation/scorers/ ---

def compute_specificity_score(candidate: CandidateCause) -> float:
    """
    Score how specific a candidate is. 0.0 = generic, 1.0 = highly specific.
    Used to penalize vague hypotheses in the scoring engine.
    """
    text = f"{candidate.description} {candidate.triggering_event} {candidate.affected_service}"
    score = 0.0

    # Exact entity references
    specific_indicators = [
        "commit", "version", "v", "sha", "pod", "instance", "shard", "replica",
        "p99", "p95", "latency", "cpu", "memory", "disk", "timeout", "ms",
        "deployment", "rollback", "config", "flag", "feature flag"
    ]
    for indicator in specific_indicators:
        if indicator in text.lower():
            score += 0.15

    # Evidence anchoring
    score += min(len(candidate.evidence_support) * 0.1, 0.3)

    # Runbook grounding
    score += min(len(candidate.runbook_matches) * 0.05, 0.2)

    # Penalize vague length (overly long descriptions often hedge)
    if len(candidate.description) > 300:
        score -= 0.1

    return min(max(score, 0.0), 1.0)


def compute_evidence_coverage(candidate: CandidateCause, narrative: SynthesizedNarrative) -> float:
    """
    What fraction of the synthesized anomalies does this candidate explain?
    """
    if not narrative.anomalies:
        return 0.0

    # Simple heuristic: count evidence_support that maps to anomaly services
    explained = set()
    for evidence_id in candidate.evidence_support:
        for item in narrative.timeline:
            if item.evidence_id == evidence_id:
                explained.add(item.service)

    anomaly_services = {a.split(":")[0] for a in narrative.anomalies}
    if not anomaly_services:
        return 0.0

    return len(explained.intersection(anomaly_services)) / len(anomaly_services)
